### ISSUE TITLE
查询接口返回结果中怎么获取rank排名呢

### ISSUE THREAD

**Issue by jobmission** [hl845740757/java-zset#2]
查询接口返回结果中怎么获取rank排名呢，如zrevrangeByRank、zrangeByRank

**Comment by hl845740757** [comment]
start加你当前遍历的索引...
```
List list  = zrangeByRank(start, end)
int rank = -1;
for (int idx = 0; idx < list.size(); idx++) {
    rank = start + idx;
}
```

再笨拙一点 zrank 查...
不过目前根据分数段查询的话还是存在不方便，只能zrank查询，如果为了方便的话，可以在返回的Entry上添加获取rank的接口
