### ISSUE TITLE
依赖太大了 fastutil

### ISSUE THREAD

**Issue by jobmission** [hl845740757/java-zset#4]
fastutil这个依赖太大了，二十多M

**Comment by hl845740757** [comment]
你这个需求不容易解决。
我不会去实现基础类型的map，这很难保证质量；目前想到的方案是打包的时候不打依赖包，但不打依赖包，你就不可以使用特定类型的zset

**Comment by hl845740757** [comment]
你不说我都没注意它有这么大...
我去看了下官方，官方已经意识到这个问题了，拆分了两个jar包
不过core包仍然有6M
