### ISSUE TITLE
zcount 代码有BUG

### ISSUE THREAD

**Issue by a610569731** [hl845740757/java-zset#5]
ScoreRangeSpec<Long> range = new ScoreRangeSpec(100000l,false,200000l,false);
        int counts =  zSet.zcount(range);

返回了12万

**Comment by hl845740757** [comment]
感谢你积极反馈。
通常我们在提交bug的时候，如果认为结果是错误的，需要同时告知期望值，即：正确的结果是什么。
不知道你认为有Bug的时候有没有查看过堆数据，正确的计数应该是多少？
你现在提供的信息有点少，我没法去排查问题

**Comment by a610569731** [comment]
ComplexScoreHandler s = new ComplexScoreHandler();
        ComplexStringHandler key = new ComplexStringHandler();
        final GenericZSet<String, Long> zSet = GenericZSet.newGenericKeyZSet(key, s);
        LongStream.rangeClosed(0, 200000l).forEach(playerId -> {
            zSet.zadd(playerId, playerId + "");
        });
        System.out.println(zSet.zcard());
        ScoreRangeSpec<Long> range = new ScoreRangeSpec(100000l, false, 200000l, false);
        int tempCount = zSet.zcount(range); //返回了 132177有时90000  正确应该是100001

**Comment by hl845740757** [comment]
你的 ScoreHandler 或 KeyHandler 比较实现可能有误，常犯的错误是：
```
   if (a > b) return 1;
   return -1;
```

```
    private static class ComplexStringHandler implements Comparator<String> {

        @Override
        public int compare(String o1, String o2) {
            return o1.compareTo(o2);
        }
    }

    private static class ComplexScoreHandler implements ScoreHandler<Long> {

        @Override
        public int compare(Long o1, Long o2) {
            return o1.compareTo(o2);
        }

        @Override
        public Long sum(Long oldScore, Long increment) {
            throw new UnsupportedOperationException();
        }
    }
```

```
    Connected to the target VM, address: '127.0.0.1:11380', transport: 'socket'
    200001
    100001
    Disconnected from the target VM, address: '127.0.0.1:11380', transport: 'socket'
```

**Comment by a610569731** [comment]
好的感谢
